apiVersion: v1
kind: Secret
metadata:
  name: processor-secrets
  namespace: apps
type: Opaque
stringData:
  DB_DSN: "postgresql://admin:CHANGE_ME@postgres.platform.svc.cluster.local:5432/vidport"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: ghcr.io/quazzar7/vidport-processor:latest
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka.platform.svc.cluster.local:9092
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: processor-secrets
                  key: DB_DSN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
