apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vidport-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quazzar7/VidPort.git
    targetRevision: main
    path: k8s/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
